// Textos da interface. Um lugar só, pra que "abrir pra outras línguas" um dia seja
// trocar este arquivo — e não caçar 300 literais. Só o que já migrou pro React
// entra aqui; o legado ainda tem os textos dele inline.

export const strings = {
  login: {
    charAlt: 'Personagem',
    eyebrow: '✦ SISTEMA DE ESTUDOS ✦',
    title: ['STUDY', 'PETS'],
    sub: ['Transforme sua rotina de estudos', 'numa aventura. Suba de nível. Evolua.'],
    features: [
      { icon: '⚡', label: ['Pomodoro', 'inteligente'] },
      { icon: '📊', label: ['Analytics', 'pessoal'] },
      { icon: '🎮', label: ['XP &', 'Níveis'] },
    ],
    google: 'Continuar com Google',
    finePrint: 'Dados salvos na nuvem · Sincronizado em todos os dispositivos',
  },
  tabs: {
    plano: '📚 Plano',
    analise: '📊 Análise',
    perfil: '🧑 Perfil',
  },
  header: {
    sair: 'Sair',
    xp: (total: number) => `${total} XP`,
  },
  plan: {
    xpTotal: 'XP Total',
    weekXp: (xp: number) => `Semana: ${xp} XP`,
    todayNone: 'Hoje: —',
    todayPending: (xp: number, coins: number) => `Hoje: +${xp} XP · +${coins} 🪙`,
    todayClosed: '✓ Hoje encerrado',
    stats: { estudos: 'Estudos', pausas: 'Pausas', semana: 'Semana' },
    weekChecks: (n: number) => `${n} ✓`,
    weekOption: (n: number, start: string, end: string) => `Semana ${n}  ·  ${start} – ${end}`,
    days: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
    sessions: ['Sessão 1', 'Sessão 2', 'Sessão 3', 'Sessão 4', 'Sessão 5', 'Sessão 6'],
    sessionFallback: 'Sessão',
    addEvent: '+ Evento',
    freeDay: '🌴 Dia livre',
    xpGain: (xp: number) => `+${xp} XP`,
    lunchEdit: '✏️ editar',
    lunchEdited: '✏️ editado',
    lunchTitle: 'Clique para editar o almoço de hoje',
    free: 'livre',
    eventTitle: 'Clique pra apagar este evento',
    notYet: 'Ainda não chegou 🔮',
    dayClosed: 'Dia encerrado 🔒',
    finishDay: 'Encerrar o dia',
    dayClosedBanner: 'Dia encerrado',
    floatXp: (xp: number) => `+${xp} XP`,
    floatCoins: (coins: number) => `+${coins} 🪙`,
  },
  groups: {
    button: 'Agrupar',
    cancel: 'Cancelar',
    hintFirst: 'Toque no primeiro bloco do grupo',
    hintLast: 'Agora toque no último bloco',
    hintDrag: 'Arraste até o último bloco e solte',
    hintResize: 'Solte pra ajustar o trecho',
    panelNew: '✏️ Novo grupo',
    panelEdit: '✏️ Editar grupo',
    summary: (start: string, end: string, count: number, dur: string) =>
      `${start} – ${end} · ${count === 1 ? '1 estudo' : `${count} estudos`} · ${dur}`,
    range: (start: string, end: string) => `${start} – ${end}`,
    name: 'Nome',
    namePlaceholder: 'Ex: Análise II, Cap. 4 de Física...',
    goal: 'Objetivo (opcional)',
    goalPlaceholder: 'Ex: terminar a lista 3',
    create: 'Criar grupo',
    save: 'Salvar',
    delete: 'Apagar grupo',
    deleted: 'Grupo apagado',
    progress: (done: number, total: number) => `${done}/${total}`,
    progressDone: (done: number, total: number) => `✓ ${done}/${total}`,
    progressMins: (done: string, total: string) => `${done} de ${total}`,
    noStudy: 'sem estudos neste trecho',
    headerTitle: 'Toque pra editar o grupo',
    gripTitle: 'Arraste pra ajustar o trecho',
    refusal: {
      closed: 'Dia encerrado 🔒',
      'end-before-start': 'O fim tem que ser depois do início.',
      overlap: 'Já existe um grupo nesse trecho.',
      'no-study': 'Escolha um trecho com pelo menos um estudo.',
      'not-found': 'Esse grupo não existe mais.',
    },
  },
  events: {
    panel: {
      title: '📅 Novo Evento',
      tip1Title: 'Considere o deslocamento até a aula.',
      tip1: 'Antes de qualquer compromisso você precisa sair da sala de estudo e ir até o lugar do evento — isso leva tempo. Se a aula começa às 11:30 e o caminho leva uns 15 minutos, defina o evento a partir das 11:15. Assim os pomodoros param na hora certa e você não fica no meio de um bloco quando precisar sair.',
      tip2Title: 'E o tempo depois também.',
      tip2: 'Quando o evento acaba, geralmente tem um intervalo até você voltar a estudar. Considere adicionar 15 minutos ao fim do evento.',
      name: 'Nome do evento',
      namePlaceholder: 'Ex: Aula de Álgebra, Consulta...',
      time: 'Horário',
      start: 'Início',
      end: 'Fim',
      counts: 'Conta como estudo (dá XP e moedas)',
      countsHint: 'Marca pra aula, prova, palestra etc. (vira bloco de estudo, com check e XP). Desliga pra consulta, reunião, evento social etc. (bloqueia o tempo, sem XP).',
      repeat: 'Repetir este evento',
      weekdays: 'Dias da semana',
      freq: 'Frequência',
      freqs: { weekly: 'Toda semana', biweekly: 'A cada 2 semanas', monthly: 'Mensalmente' },
      until: 'Até',
      noEnd: 'Sem fim',
      cancel: 'Cancelar',
      add: 'Adicionar',
      validation: {
        'end-before-start': 'O horário de fim deve ser depois do início.',
        'no-weekdays': 'Escolha pelo menos um dia da semana pra repetição.',
      },
    },
    remove: {
      title: '📅 Apagar evento?',
      singleText: ['Vai apagar o evento ', '. Os checks ligados a ele somem junto.'],
      seriesText: ['Este evento faz parte de uma série recorrente (', '). Quer apagar só este dia ou toda a série?'],
      cancel: 'Cancelar',
      onlyToday: 'Só este dia',
      delete: 'Apagar',
      deleteSeries: 'Apagar a série',
    },
    lunch: {
      title: '🍽️ Editar Almoço',
      onlyThisDay: 'Alteração válida só para este dia.',
      timeAndDuration: 'Horário e duração',
      start: 'Início',
      duration: 'Duração (min)',
      reset: '↺ Padrão',
      save: 'Salvar',
    },
  },
  session: {
    loadError: '⚠️ Erro ao carregar dados',
  },
  onboarding: {
    title: '👋 Bem-vindo!',
    intro: 'Vamos configurar quando você quer usar o app. Você pode mudar isso depois nas configurações.',
    period: 'Período de uso',
    start: 'Início',
    end: 'Fim',
    useAlways: 'Usar sempre (sem data fim)',
    alwaysToast: 'Modo "sempre" — até o fim do ano',
    skipWeekends: 'Pular finais de semana (sáb e dom)',
    begin: 'Começar',
    endBeforeStart: '⚠️ Data fim antes da data início',
    starterTitle: '🐾 Escolha seu companheiro',
    starterIntro: 'Ele estuda com você desde o primeiro bloco e ganha XP junto. Escolhe um e dá um nome.',
    starterNotice: 'Sem estresse: todos os outros dá pra adotar depois, na loja, com as moedas que você ganha estudando.',
    traits: {
      dog: 'Fiel. Comemora o seu primeiro estudo do dia.',
      cat: 'Independente. Rende mais depois de uma pausa longa.',
      snake: 'Paciente. Fica forte quando você bate a meta do dia.',
      cow: 'Tranquila. Rende mais depois do almoço.',
      dove: 'Madrugadora. Rende mais antes das 9h.',
    },
    next: 'Continuar',
    back: '← Trocar de pet',
    starterMissing: 'Escolhe um pet e dá um nome pra ele.',
  },
  dayEnd: {
    confirmTitle: 'Encerrar o dia?',
    confirmText: ['Isso vai ', 'creditar o XP', ' dos blocos marcados de hoje (no usuário e no pet equipado) e ', 'travar os checks', ' deste dia.'],
    confirmFinal: 'Decisão final — não dá pra reabrir o dia depois.',
    cancel: 'Cancelar',
    confirm: 'Encerrar dia',
    summaryTitle: '🎉 Dia encerrado',
    xp: 'XP',
    coins: 'Moedas',
    levelUp: (level: number, name: string) => `Subiu pro nível ${level} — ${name}!`,
    petLevelUp: (from: number, to: number) => `Lv. ${from} → ${to} ✨`,
    empty: ['Nenhum bloco marcado hoje.', 'Dia encerrado sem ganhos.'],
    continue: 'Continuar',
    promptTitle: '🌙 Passou do horário',
    promptIntro: (lastEnd: string) => `O último bloco de estudo (${lastEnd}) já passou. O que você quer fazer?`,
    promptFinishTitle: 'Encerrar o dia',
    promptFinishSub: 'Creditar XP, travar checks. Decisão final.',
    promptExtendTitle: 'Prolongar estudos',
    promptExtendSub: 'Mudar o horário de fim do dia.',
    newEnd: 'Novo horário de fim',
    back: 'Voltar',
    extend: 'Prolongar',
    extended: (end: string) => `Fim do dia: ${end} ⏰`,
  },
  profile: {
    name: 'Estudante',
    nextLevel: 'próximo nível',
    max: 'MÁX',
    xpTotal: 'XP total',
    blocks: 'Blocos',
    study: 'Estudo',
    coins: 'Moedas',
    activeTag: 'Pet ativo',
    apXp: (xp: number, next: number, remaining: number, nextLevel: number) =>
      `${xp} / ${next} XP · faltam ${remaining} pro Lv. ${nextLevel}`,
    noActivePet: 'Nenhum pet equipado. Adote um na loja e equipe em "🐾 Meus pets".',
    myPets: 'Meus pets',
    shop: 'Loja de pets',
    count: (owned: number, total: number) => `${owned}/${total} ✨`,
  },
  pets: {
    shopTitle: '🛒 Loja de pets',
    myPetsTitle: '🐾 Meus pets',
    empty: ['Nenhum pet ainda.', 'Visite a loja pra adotar um!'],
    badgeActive: 'Ativa',
    lv: (n: number) => `Lv. ${n}`,
    price: (p: number) => `🪙 ${p}`,
    adopt: 'Adotar',
    equip: 'Equipar',
    equipped: '✓ Equipada',
    skills: 'Skills',
    insufficient: 'Moedas insuficientes',
    buyTitle: 'Adotar pet?',
    buyText: ['Adotar ', ' por 🪙 ', '?'],
    cancel: 'Cancelar',
    nameLabel: 'Nome',
    namePlaceholder: 'Como vai se chamar?',
    nameDice: 'Sortear outro nome',
    nameInvalid: 'O nome precisa ter de 1 a 16 caracteres.',
    adopted: (name: string) => `${name} chegou! 🐾`,
    rename: 'Renomear',
    renameTitle: '✏️ Renomear',
    save: 'Salvar',
    evolve: '✨ Evoluir',
    evolveHint: (level: number) => `Evolui no Lv. ${level}`,
    evolveTitle: (name: string) => `✨ ${name} pode evoluir`,
    evolveChoose: 'Escolha o caminho. A escolha é definitiva — nome, XP e nível continuam.',
    evolveAdvance: (form: string) => `Próximo estágio: ${form}. Nome, XP e nível continuam.`,
    evolveConfirm: 'Evoluir',
    evolved: (name: string, form: string) => `${name} evoluiu: ${form}! ✨`,
  },
  analytics: {
    toNext: (xp: number, name: string) => `Faltam ${xp} XP para ${name}`,
    maxLevel: 'Nível máximo atingido! 🏆',
    sparkline: 'Tendência (8 sem)',
    sparklineTitle: (mins: readonly number[]) => `Últimas 8 semanas: ${mins.map((m) => `${m}min`).join(' · ')}`,
    views: { hoje: 'Hoje', semana: 'Semana', geral: 'Geral', recordes: 'Recordes' },
    adhToday: 'Realizado hoje',
    adhWeek: 'Realizado na semana',
    adhAll: 'Realizado no geral',
    adhVal: (done: number, planned: number) => `${done} / ${planned} min`,
    adhValNone: '— / — min',
    adhSub: (doneH: number, plannedH: number) => `${doneH}h de ${plannedH}h`,
    noData: 'sem dados ainda',
    goalHeadline: ['Você bateu a meta de ', 'min em ', ' esta semana'],
    day: 'dia',
    days: 'dias',
    dotWeekend: (d: string) => `${d} — fim de semana pausado`,
    dotFuture: (d: string) => `${d} — futuro`,
    dotMet: (d: string, done: number) => `${d}: ${done} min ✓`,
    dotMiss: (d: string, done: number, min: number) => `${d}: ${done} min (meta ${min})`,
    dropoffTitle: 'Conclusão por sessão',
    historic: '(histórico)',
    dropoffEmpty: 'Ainda não há dados suficientes.',
    session: (n: number) => `Sessão ${n}`,
    heatmapTitle: 'Plano cumprido — 16 semanas',
    cellFuture: (d: string) => `${d} — futuro`,
    cellWeekend: (d: string) => `${d} — fim de semana`,
    cellValue: (d: string, today: boolean, done: number, goal: number, pct: number) =>
      `${d}${today ? ' (hoje)' : ''}: ${done} de ${goal} min (${pct}%)`,
    hoursTitle: 'Horários onde mais estuda',
    hourTitle: (h: number, count: number) => `${h}h: ${count} blocos concluídos`,
    blocksDone: 'Blocos feitos',
    daysInRow: 'Dias seguidos',
    bestWeek: 'Melhor semana',
    curStreak: '🔥 Sequência atual',
    bestStreak: '🏆 Maior sequência',
    bestDay: '📖 Melhor dia (blocos)',
    bestXp: '⚡ XP num único dia',
    daysCount: (n: number) => `${n} dias`,
  },
  settings: {
    fab: 'Configurações',
    back: '← Voltar',
    title: 'Configurações',
    tabs: { day: 'Rotina', general: 'Geral' },
    reset: '↺ Padrão',
    save: 'Salvar',
    incomplete: 'Preencha todos os campos antes de salvar.',
    summary: {
      title: 'Resumo do dia',
      desc: 'Como fica um dia cheio com a configuração abaixo.',
      warn: {
        incomplete: 'Preencha todos os campos para ver o resumo.',
        'no-windows': 'Adicione pelo menos uma janela de estudo válida.',
        'no-blocks': 'Essa combinação não gera nenhum bloco. Ajuste as janelas ou as durações.',
      },
      tiles: { pomos: 'pomos', study: 'estudo', pauses: 'pausas', xp: 'XP/dia' },
      xpApprox: (xp: number) => `~${xp}`,
      windows: (n: number) => `Distribuídos em ${n} janelas de estudo.`,
      noteOk: (end: string) => `Fecha o dia às ${end}, certinho no fim da última janela.`,
      noteOver: (diff: number, end: string) => `Passa ${diff}min das ${end} — o último bloco vaza da janela.`,
      noteUnder: (actual: string, diff: number, end: string) =>
        `Para às ${actual}, ${diff}min antes das ${end} — sobra um tempo sem bloco.`,
    },
    windows: {
      title: 'Janelas de estudo',
      add: '+ Adicionar',
      desc: 'Os intervalos do dia em que você estuda. Valem para todos os dias — para compromissos pontuais, use Eventos.',
      startLabel: 'Início da janela',
      endLabel: 'Fim da janela',
      remove: 'Remover janela',
      endBeforeStart: 'fim antes do início',
      atLeastOne: 'Pelo menos uma janela é necessária.',
    },
    lunch: {
      title: 'Almoço',
      desc: 'Fica reservado todo dia, e o plano se organiza em volta dele.',
      toggle: 'Reservar horário de almoço',
      toggleSub: 'Desligue se você prefere almoçar em horários variáveis.',
      start: 'Começa às',
      duration: 'Duração (min)',
    },
    rhythm: {
      title: 'Ritmo do pomodoro',
      desc: 'A duração de cada bloco. A pausa longa entra a cada 4 pomodoros.',
      study: 'Estudo (min)',
      short: 'Pausa curta (min)',
      long: 'Pausa longa (min)',
      fit: '🎯 Encaixar estudo nos meus horários',
      fitHint: 'Testa combinações de duração e mostra as que melhor preenchem suas janelas, sem sobrar tempo morto.',
    },
    period: {
      title: 'Período de uso',
      desc: 'O intervalo em que você quer ganhar XP e acompanhar seu progresso.',
      start: 'Início',
      end: 'Fim',
      startFixed: 'O início da sessão é fixo. Use Cancelar sessão pra recomeçar.',
      hint: 'O início é fixo — só muda cancelando a sessão.',
      clearEnd: 'Usar sem data de fim',
      skipWeekends: 'Pular finais de semana',
      skipWeekendsSub: 'Sábado e domingo ficam livres, sem blocos e sem cobrança de meta.',
    },
    goal: {
      title: 'Meta diária',
      desc: 'Quanto você precisa estudar num dia para manter a sequência e ganhar o bônus de moedas.',
      label: 'Minutos por dia (15–240)',
    },
    danger: {
      title: 'Zona de perigo',
      cancelTitle: 'Cancelar sessão',
      cancelDesc: 'Apaga checks, eventos, pets e configurações, e reabre o onboarding. Sua conta continua existindo.',
      cancelBtn: 'Cancelar sessão',
      deleteTitle: 'Apagar minha conta',
      deleteDesc: 'Remove a conta e todos os dados do servidor. Você é desconectado e nada pode ser recuperado.',
      deleteBtn: 'Apagar conta',
    },
    fit: {
      title: '🎯 Encaixar estudo',
      intro: '💡 Diz como você gosta de estudar e eu sugiro 3 combinações que melhor encaixam nas janelas livres do dia visível (respeita início, fim, almoço e eventos).',
      pomo: 'Pomodoro ideal (min)',
      short: 'Pausa curta ideal (min)',
      long: 'Pausa longa ideal (min)',
      flex: 'Aceito flexibilidade de',
      flexOption: (n: number) => `±${n} min`,
      cancel: 'Cancelar',
      run: 'Calcular sugestões',
      none: 'Não encontrei combinações válidas. Aumente a flexibilidade ou ajuste os ideais.',
      best: '✨ Recomendada',
      option: (n: number) => `Opção ${n}`,
      stats: { pomo: 'Pomo', short: 'Pausa', long: 'Longa' },
      meta: (count: number, dur: string, end: string) => `${count} estudos · ${dur} efetivos · termina às ${end}`,
      apply: 'Aplicar',
      applied: 'Sugestão preenchida — clica em Salvar pra confirmar',
    },
    cancel: {
      title: '⚠️ Cancelar sessão?',
      intro: 'Isso vai apagar ',
      introStrong: 'tudo',
      items: ['Todos os checks feitos', 'Eventos e ajustes de almoço', 'Pets adotados e moedas', 'Configurações personalizadas'],
      outro: 'Depois você vai começar do zero, como uma conta nova. ',
      outroStrong: 'Esta ação não pode ser desfeita.',
      back: 'Voltar',
      confirm: 'Sim, cancelar',
      done: 'Sessão cancelada — começando do zero',
    },
    deleteAccount: {
      title: '🗑️ Apagar sua conta?',
      intro: 'Isso apaga ',
      introStrong: 'a conta inteira',
      introRest: ', não só a sessão:',
      items: ['Todo o histórico de checks, XP e moedas', 'Eventos, séries recorrentes e ajustes de almoço', 'Pets adotados e skills', 'Seu acesso — você será desconectado'],
      outro: 'Nada disso pode ser recuperado. Se você só quer recomeçar do zero mantendo a conta, use ',
      outroStrong: 'Cancelar sessão',
      typeToConfirm: ['Digite ', 'APAGAR', ' pra confirmar'],
      keyword: 'APAGAR',
      back: 'Voltar',
      confirm: 'Apagar para sempre',
      status: {
        deleting: 'Apagando...',
        reauth: 'Confirme com o Google pra finalizar...',
        'no-user': 'Ninguém logado',
        'data-failed': '⚠️ Não deu pra apagar seus dados. Tenta de novo.',
        'reauth-failed': '⚠️ Seus dados foram apagados, mas a conta continua. Entre de novo e repita pra concluir.',
        'delete-failed': '⚠️ Seus dados foram apagados, mas não deu pra remover a conta. Tenta de novo.',
      },
      done: 'Conta apagada. Até mais 👋',
    },
  },
  timer: {
    inProgress: 'Em andamento',
    startsIn: 'Começa em',
    stop: '✕ Parar',
    mute: 'Silenciar',
    refusal: (r: { reason: 'not-today' } | { reason: 'ended' }) =>
      r.reason === 'not-today' ? 'Só dá pra iniciar timer em blocos de hoje 📅' : 'Este bloco já terminou ⏎',
    /** "✓ Estudo 3 concluído · +50 XP · +25 🪙" — a faixa no foco e o toast no plano. */
    completed: (c: { name: string; type: string; xp: number; coins: number }) =>
      `✓ ${c.name} ${c.type === 'pausa' ? 'concluída' : 'concluído'}` +
      (c.xp ? ` · +${c.xp} XP` : '') +
      (c.coins ? ` · +${c.coins} 🪙` : ''),
    notification: {
      study: '📖 Estudo concluído! Hora da pausa.',
      break: '🧘 Pausa concluída! Hora de estudar.',
    },
    focus: {
      exit: '← Sair do foco',
      chip: (session: string, n: number) => `${session} · Bloco ${n}`,
      pomodoroOf: (min: number) => `Pomodoro de ${min} min`,
      breakOf: (min: number) => `Pausa de ${min} min`,
      completed: (pct: number) => `completou · ${pct}%`,
      startsAt: (time: string) => `começa às ${time}`,
      onComplete: ' ao concluir',
      next: 'Em seguida',
      endOfDay: 'Fim do dia 🌙',
      minutes: (min: number) => `${min} min`,
    },
  },
} as const;
