// Textos da interface. Um lugar só, pra que "abrir pra outras línguas" um dia seja
// trocar este arquivo — e não caçar 300 literais. Só o que já migrou pro React
// entra aqui; o legado ainda tem os textos dele inline.

export const strings = {
  login: {
    charAlt: 'Personagem',
    eyebrow: '✦ SISTEMA DE ESTUDOS ✦',
    title: ['STUDY', 'PETS'],
    sub: ['Transforme sua rotina de estudos', 'numa aventura. Suba de nível. Evolua.'],
    features: [
      { icon: '⚡', label: ['Pomodoro', 'inteligente'] },
      { icon: '📊', label: ['Analytics', 'pessoal'] },
      { icon: '🎮', label: ['XP &', 'Níveis'] },
    ],
    google: 'Continuar com Google',
    finePrint: 'Dados salvos na nuvem · Sincronizado em todos os dispositivos',
  },
  tabs: {
    plano: '📚 Plano',
    analise: '📊 Análise',
    perfil: '🧑 Perfil',
  },
  header: {
    sair: 'Sair',
    xp: (total: number) => `${total} XP`,
  },
  plan: {
    xpTotal: 'XP Total',
    weekXp: (xp: number) => `Semana: ${xp} XP`,
    todayNone: 'Hoje: —',
    todayPending: (xp: number, coins: number) => `Hoje: +${xp} XP · +${coins} 🪙`,
    todayClosed: '✓ Hoje encerrado',
    stats: { estudos: 'Estudos', pausas: 'Pausas', semana: 'Semana' },
    weekChecks: (n: number) => `${n} ✓`,
    weekOption: (n: number, start: string, end: string) => `Semana ${n}  ·  ${start} – ${end}`,
    days: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
    sessions: ['Sessão 1', 'Sessão 2', 'Sessão 3', 'Sessão 4', 'Sessão 5', 'Sessão 6'],
    sessionFallback: 'Sessão',
    addEvent: '+ Evento',
    freeDay: '🌴 Dia livre',
    xpGain: (xp: number) => `+${xp} XP`,
    lunchEdit: '✏️ editar',
    lunchEdited: '✏️ editado',
    lunchTitle: 'Clique para editar o almoço de hoje',
    free: 'livre',
    eventTitle: 'Clique pra apagar este evento',
    notYet: 'Ainda não chegou 🔮',
    dayClosed: 'Dia encerrado 🔒',
    finishDay: 'Encerrar o dia',
    dayClosedBanner: 'Dia encerrado',
    floatXp: (xp: number) => `+${xp} XP`,
    floatCoins: (coins: number) => `+${coins} 🪙`,
  },
  events: {
    panel: {
      title: '📅 Novo Evento',
      tip1Title: 'Considere o deslocamento até a aula.',
      tip1: 'Antes de qualquer compromisso você precisa sair da sala de estudo e ir até o lugar do evento — isso leva tempo. Se a aula começa às 11:30 e o caminho leva uns 15 minutos, defina o evento a partir das 11:15. Assim os pomodoros param na hora certa e você não fica no meio de um bloco quando precisar sair.',
      tip2Title: 'E o tempo depois também.',
      tip2: 'Quando o evento acaba, geralmente tem um intervalo até você voltar a estudar. Considere adicionar 15 minutos ao fim do evento.',
      name: 'Nome do evento',
      namePlaceholder: 'Ex: Aula de Álgebra, Consulta...',
      time: 'Horário',
      start: 'Início',
      end: 'Fim',
      counts: 'Conta como estudo (dá XP e moedas)',
      countsHint: 'Marca pra aula, prova, palestra etc. (vira bloco de estudo, com check e XP). Desliga pra consulta, reunião, evento social etc. (bloqueia o tempo, sem XP).',
      repeat: 'Repetir este evento',
      weekdays: 'Dias da semana',
      freq: 'Frequência',
      freqs: { weekly: 'Toda semana', biweekly: 'A cada 2 semanas', monthly: 'Mensalmente' },
      until: 'Até',
      noEnd: 'Sem fim',
      cancel: 'Cancelar',
      add: 'Adicionar',
      validation: {
        'end-before-start': 'O horário de fim deve ser depois do início.',
        'no-weekdays': 'Escolha pelo menos um dia da semana pra repetição.',
      },
    },
    remove: {
      title: '📅 Apagar evento?',
      singleText: ['Vai apagar o evento ', '. Os checks ligados a ele somem junto.'],
      seriesText: ['Este evento faz parte de uma série recorrente (', '). Quer apagar só este dia ou toda a série?'],
      cancel: 'Cancelar',
      onlyToday: 'Só este dia',
      delete: 'Apagar',
      deleteSeries: 'Apagar a série',
    },
    lunch: {
      title: '🍽️ Editar Almoço',
      onlyThisDay: 'Alteração válida só para este dia.',
      timeAndDuration: 'Horário e duração',
      start: 'Início',
      duration: 'Duração (min)',
      reset: '↺ Padrão',
      save: 'Salvar',
    },
  },
  timer: {
    inProgress: 'Em andamento',
    stop: '✕ Parar',
    mute: 'Silenciar',
    refusal: (r: { reason: 'not-today' } | { reason: 'ended' } | { reason: 'not-started'; minutesUntil: number }) =>
      r.reason === 'not-today'
        ? 'Só dá pra iniciar timer em blocos de hoje 📅'
        : r.reason === 'ended'
          ? 'Este bloco já terminou ⏎'
          : `Este bloco começa em ${r.minutesUntil} min ⏳`,
    notification: {
      study: '📖 Estudo concluído! Hora da pausa.',
      break: '🧘 Pausa concluída! Hora de estudar.',
    },
    focus: {
      exit: '← Sair do foco',
      chip: (session: string, n: number) => `${session} · Bloco ${n}`,
      pomodoroOf: (min: number) => `Pomodoro de ${min} min`,
      breakOf: (min: number) => `Pausa de ${min} min`,
      completed: (pct: number) => `completou · ${pct}%`,
      onComplete: ' ao concluir',
      next: 'Em seguida',
      endOfDay: 'Fim do dia 🌙',
      minutes: (min: number) => `${min} min`,
    },
  },
} as const;
